### ISSUE TITLE
Events page empty despite knowing there are prior events

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#1051]
I have noticed that the events page could be empty even though i know there are events

**Comment by seesemichaelj** [comment]
I'm having issues reproducing this (and always had). Maybe I'm going crazy? Maybe it got fixed? I'm going to close this one and hope it's fixed or someone else will have repro steps.

**Comment by jopasserat** [comment]
I'm having troubles with events as well. Not the simplest workflow to reproduce but here are a few indications plus code highlights:
  - using Ganache v2.0.0-beta.2, on Debian testing, via AppImage
  - on this project https://github.com/jopasserat/eve

Details on what I've observed:
  - cannot see any event in the interface, but they're **definitely fired since they are part of the code's logic**
  - this frontend function should trigger two `events` https://github.com/jopasserat/eve/blob/enh_refactor%2BdocumentVotingWorkflow/demo/eve-ui/imports/voting.coffee#L49-L79
  - the first one is a `ComputeTask` event, part of the business logic, and is fired when [this function](https://github.com/jopasserat/eve/blob/enh_refactor%2BdocumentVotingWorkflow/contracts/enigma/Enigma.sol#L178-L201) is called from the [Voting contract](https://github.com/jopasserat/eve/blob/enh_refactor%2BdocumentVotingWorkflow/contracts/Voting.sol#L45-L53)
  - events are successfully fetched and processed [here](https://github.com/jopasserat/eve/blob/enh_refactor%2BdocumentVotingWorkflow/demo/eve-ui/imports/voting.coffee#L56-L64), but **do not show up in the Ganache UI**
  - a second event `TalliedVotes` is triggered when calling [this function](https://github.com/jopasserat/eve/blob/enh_refactor%2BdocumentVotingWorkflow/contracts/Voting.sol#L58-L62) at the end of the same [front-end function](https://github.com/jopasserat/eve/blob/enh_refactor%2BdocumentVotingWorkflow/demo/eve-ui/imports/voting.coffee#L71-L73) but **still nothing appears in Ganache UI**

Hope this helps, and thanks for the great work, new UI is really slick!

**Comment by seesemichaelj** [comment]
Thanks @jopasserat for reporting this and providing some reproduction steps! Glad you're liking the new UI other then this issue :sweat_smile: 

I'll reopen this issue and let the team that's taking over the UI development from me triage this issue given your steps.

**Comment by jopasserat** [comment]
FYI i now see the events on the same dApp after updating to 2.0.0 stable.
:+1:

**Comment by seesemichaelj** [comment]
Woo! Thank you so much @jopasserat for reporting this back to us. I'm going to go ahead and close it now :)
