### ISSUE TITLE
Ganache is not closing processes on Windows

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#1055]
This is reported by @davidburela from this [tweet](https://twitter.com/DavidBurela/status/1075963625519702016):

>I quit Ganache, it isn't on the taskbar, but it is still running somewhere in the background

![image](https://user-images.githubusercontent.com/549323/50324896-9bbaa880-04af-11e9-9de4-ed9bbe2c1eaf.png)

**Comment by sarbogast** [comment]
Same thing on MacOS. Because of that, if I just restart Ganache, it tells me that port 7545 is already used.

**Comment by seesemichaelj** [comment]
I found the issue for Windows (in https://github.com/trufflesuite/ganache/commit/cc61ec81664ed8981679d721d3acbf145f6a2b91), which does make sense why Windows would have issues but Linux/Mac wouldn't. I do believe that https://github.com/trufflesuite/ganache/commit/cc61ec81664ed8981679d721d3acbf145f6a2b91 should fix this issue.

I'm going to go ahead and close this unless @sarbogast believes that it won't fix it. Otherwise, this fix should be available in the next beta release (ETA next week)

**Comment by sarbogast** [comment]
Indeed, it seems that the running process stays only for a few seconds, then it disappears.

**Comment by seesemichaelj** [comment]
Awesome! I believe the fix for this issue will kill that process immediately going forward rather than letting it run for a few seconds

**Comment by balexander4** [comment]
This is occurring for me again when I close Ganache using the dock on Darwin, (right clicking and hitting quit, instead of using the x). The processes remain open running in the background causing the port error issues mentioned above.

Steps to reproduce:
1. Open Activity Monitor to view open processes for Electron.
2. Open a new instance of Ganache 2.0.0.2 and choice an existing workspace.
3. Right click on the Ganache icon and select Quit to close. Do not use the left hand corner red X to close Ganache.
4. View open processes in the Activity Monitor. You should still see Electron processes running on the Activity Monitor even after Ganache has been closed. 
5. Reopen Ganache and notice that there is an error about ports being already open on the Server tab. "The port is used by another application; please change it"

Running:
Mac High Sierra 10.13.6 
Ganache 2.0.0.2

**Comment by seesemichaelj** [comment]
Closing this as @balexander4's comment poses a new issue: #1129
