### ISSUE TITLE
Ganache UI not linking my truffle project

### ISSUE THREAD

**Issue by dgrmunch** [trufflesuite/ganache#1078]
## Expected Behavior

Ganache should link my contracts from my truffle-config.js

## Current Behavior

The Contracts tab displays: "To see rich contract data compile the contracts within your Truffle Project". I have already compiled and even migrated my contracts so I suppose that there is something wrong. 

## Possible Solution

Maybe my truffle-config.js has something wrong? Here the file (removing mnemonic for security reasons):

const path = require("path");
var HDWalletProvider = require("truffle-hdwallet-provider");

var mnemonic = "CHANGE_ME"; //Not my real mnemonic

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  contracts_build_directory: path.join(__dirname, "client/src/contracts"),
  networks: {
    development: {
      host: "localhost", //My ganache network
      port: 9545,
      network_id: "*" // Match any network id
    },
    ropsten: {
      provider: function() {
        return new HDWalletProvider(mnemonic, "https://ropsten.infura.io/<INFURA_Access_Token>")
      },
      network_id: 3
    }, 
    alastria: {
      host: "34.234.56.789",
      port: 22000,
      gasPrice: 0,
      network_id: "*" //1140
    },
  }
};

## Steps to Reproduce (for bugs)

Link a project with that truffle-config.js and the standard truffle project with migrations, contract, etc... folders.

## Context

Already provided

## Your Environment

MAC OS X

**Comment by seesemichaelj** [comment]
I don't think there's something wrong with your config. I'm guessing there's something just wrong in [projectFsWatcher.js](https://github.com/trufflesuite/ganache/blob/develop/src/truffle-integration/projectFsWatcher.js) that isn't reading the custom directory correctly

**Comment by dgrmunch** [comment]
I will wait for your confirmation to download an updated version then ;)
Thanks!

**Comment by honestbonsai** [comment]
Hmm interesting, I can reproduce through the `drizzle-box`.

1. `mkdir box`
1. `cd box`
1. `truffle unbox drizzle`
1. Start Ganache
1. Link Ganache to the `truffle-config.js` (which is basically empty from the fresh box)
1. `truffle compile && truffle migrate`

**Comment by seesemichaelj** [comment]
That probably confirms my hypothesis that [overriding the default contracts build directory](https://github.com/truffle-box/drizzle-box/blob/master/truffle-config.js#L6) is the source of the issue

I'd suspect `metacoin-box` is fine

**Comment by cds-amal** [comment]
@dgrmunch keeping your config the way it is, does creating a `build` folder in your truffle root (execute  `$ mkdir build`) make ganache start processing the contracts?
truffle-contract has a `build-directory` and a `contracts-build-directory` that seems ambiguous.

**Comment by honestbonsai** [comment]
@seesemichaelj Can confirm, once I comment out the changed build directory and run compile and migrate, the contracts show up in Ganache.

**Comment by seesemichaelj** [comment]
@honestbonsai the issue is probably located in `src/truffle-integration/projectFsWatcher.js`

**Comment by honestbonsai** [comment]
Truffle's `build_directory` can be independent from its `contracts_build_directory`,  however, Ganache seems to treat `build_directory` as the direct parent of `contracts_build_directory`.

When `truffle-config.js` has nothing set for `build_directory` (which isn't actually in the Truffle docs), it defaults to `./build`. When you set `contracts_build_directory` but not `build_directory` it doesn't start monitoring the contracts since `contracts_build_directory` isn't a child of `build_directory`.

**Comment by seesemichaelj** [comment]
A couple of things to note:
- The directory-by-directory watching is due to the fact that the recursive option is [not supported on Linux](https://nodejs.org/docs/latest/api/fs.html#fs_caveats)
- @honestbonsai is correct: the entire purpose of `projectFsWatcher.js` is to detect when there are new/changed/removed contract artifacts in `contracts_build_directory`

I guess my assumption that `build_directory` had to be the parent of `contracts_build_directory` was silly (though this confuses me what `build_directory` does anyway [apparently @gnidan says that it probably should be deprecated]). I'm not sure if just using relative paths will necessary work. The concept behind the code is:

>To be able to watch for files in `contracts_build_directory`, I must watch for when `contracts_build_directory` is created. To do that, I need watch its parent (my assumption was that was `build_directory`).

Anyway, this is just not correct in the generic sense. Hypothetically, the `contracts_build_directory` can be anywhere on the OS (and does not need to be a child of `truffle_directory`), so hypothetically we would need to watch the entire path. So for `/path/to/awesome/project/artifacts/`, we'd need to listen to `/`, `/path`, `/path/to`, `/path/to/awesome`, `/path/to/awesome/project`, `/path/to/awesome/project/artifacts`. For whichever paths that don't exist, we wait for the parent to create it, then watch it

Alternatively we could continuously poll until `/path/to/awesome/project/artifacts/` exists, which is ugly (but the code would be a lot simpler/cleaner). But it also may be necessary. Apparently `contracts_build_directory` just gets `mkdirp`'s, so it's possible the child would get created before we started watching the parent. Potential race condition:
1. watch `/path/to/awesome`
1. `/path/to/awesome/project` gets created
1. `/path/to/awesome/project/artifacts` gets created
1. event tells us `/path/to/awesome/project` is created, start watching to wait for 
`/path/to/awesome/project/artifacts` to get created

I haven't noticed this race condition yet, but it is possible

I'll let you @honestbonsai implement what you see fit
