### ISSUE TITLE
I cannot see any events on event page

### ISSUE THREAD

**Issue by LeonLi000** [trufflesuite/ganache#1293]
PLATFORM: mac os
GANACHE VERSION: 2.0.1

When I run the official metacoin example, I cannot see any events on event page. But my colleague was okay, and I was pretty much the same as his environment, and I was very confused.

![image](https://user-images.githubusercontent.com/6380914/57877307-17940380-784a-11e9-9260-128e8278eb11.png)
![image](https://user-images.githubusercontent.com/6380914/57877327-24b0f280-784a-11e9-8f1f-67ec6c7abf4a.png)

**Comment by fishlao** [comment]
The same problem happened to me .

**Comment by Leandro1391** [comment]
Same problem.
PLATFORM: Windows 10 Home
GANACHE VERSION: 2.0.1

**Comment by k1rill-fedoseev** [comment]
Same problem.
PLATFORM: macOS Mojave
GANACHE VERSION: 2.0.1 & 2.0.2-beta.0

**Comment by inukaeth** [comment]
I have the same isssue,  no events displayed although I can see events in truffle as well as in my Dapp code.
 Windows 10, with Ganache version 2.0.2

**Comment by tjlian616** [comment]
Same problem here. It looks like no topic was found from the truffle contracts in projectsWatcher.js. However, miyao-gmo's PR above does not work for me...

**Comment by wowoyinwei** [comment]
Same problem.Hope it can be solved as soon as possible.

**Comment by DavidBurela** [comment]
Came here to report this same issue.
When viewing a transaction which I know to have an event in it, the UI says "no events"

Platform: Windows 10
Ganache: 2.1.0

**Comment by tcoulter** [comment]
I'm told a fix is incoming (see #1402). Stay tuned!

**Comment by romanpastu** [comment]
Same issue

**Comment by jasonhuan** [comment]
Same issue. My events show up in the logs of the truffle development console when I execute a transaction that emits an event, but the event does not show up on the transaction's page in Ganache.

MacOS 10.13 High Sierra
Ganache v2.4.0
Truffle v5.1.35

**Comment by jb33k** [comment]
Yes, this thing is broken. I can also see the event in the console.

Win 10, Ganache v2.4.0, Truffle v5.1.46

**Comment by pasusarla** [comment]
Unable to see events on the Ganache GUI transaction page, while they are visible for instance on the console and also proved to have been emitted, via mochajs assertions.

Win 10, Ganache v2.4.0, Truffle v5.1.47

**Comment by sfl0r3nz05** [comment]
I have the same problem. @pasusarla or @jb33k, have you solved the problem?

I conected Window 10 ganache 2.5 to remix in order to test the contract and as you can see, the events are emitted successfully. However, the ganache is not able to decode.

![image](https://user-images.githubusercontent.com/6643905/99462828-c845fc00-2934-11eb-8ae8-2d42452126e4.png)

**Comment by sfl0r3nz05** [comment]
I cannot see event in ganache frontend, since, the connection allowed is http
![image](https://user-images.githubusercontent.com/6643905/99544389-88bef480-29b4-11eb-95e1-703941dfa451.png)

However, it is possible decode events from the websocket server that run in background to ganache frontend:

const Web3 = require("web3");
const web3 = new Web3(`ws://${process.env.HOST_PROVIDER_GANACHE}:${process.env.PORT_PROVIDER_GANACHE}`);

In addition, the truffle-config.js must be include to deploy successfully the smart contract:

    development: {
      provider: () =>
        new HDWalletProvider(mnemonic, `ws://${process.env.HOST_PROVIDER_GANACHE}:${process.env.PORT_PROVIDER_GANACHE}`),
        network_id: "5777" // Any network (default: none)
    },

**Comment by sofianeOuafir** [comment]
has this issue been solved? Have the same issue with Version 2.5.4
