### ISSUE TITLE
System Error when running Ganache 2.0.3 on linux

### ISSUE THREAD

**Issue by mindrunner** [trufflesuite/ganache#1362]
/opt/ganache/ exists, but not /opt/ganache/src/

PLATFORM: arch linux
GANACHE VERSION: 2.0.3

EXCEPTION:
```
Error: ENOENT: no such file or directory, open '/opt/ganache/src/truffle-project-loader/index.js'
```

**Comment by ankit-pant** [comment]
To resolve this issue, I tried the following:

1. The folder '/opt/ganache' exists so I created the other folders recursively i.e. I created the folder 'src' inside '/ganache' and then created the folder 'truffle-project-loader' inside the folder '/src'
2. I then created a file called 'index.js' inside the folder 'truffle-project-loader' and inside that file pasted the code found in the ganache repository corresponding to the directory structure (src/truffle-project-loader/index.js). This file can be found at https://github.com/trufflesuite/ganache/blob/develop/src/truffle-project-loader/index.js
3. I restarted the application and it worked.

Note: You need to have root privileges in order to create the folders and the file.

Ganache version: v2.0.3
Operating System: Manjaro Linux (Arch)

**Comment by mindrunner** [comment]
Sorry, I cannot remember my context with this issue. At least I do not have this problem at the moment. Thanks for reaching out! :) Will close this.
