### ISSUE TITLE
Config screen for corda nodes needs to be smarter

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache#1560]
Node name needs to be validated (only valid X509 names allowed). (done)
Add messaging for when ports are duplicates of other nodes. (done)
Make it a little prettier. (done)
**Detect node failure and load config screen when it happens.**

**Comment by davidmurdoch** [comment]
This is detects port bind errors:

https://github.com/trufflesuite/ganache/blob/b185fb5ff3c985402ab2e6f0e537066be48fb8bb/src/integrations/corda/main/utils/network/corda.js#L289-L298

**Comment by davidmurdoch** [comment]
This is where this rejection is caught and rethrown. The rethrown error is what eventually triggers the System Error dialogue in the UI.

https://github.com/trufflesuite/ganache/blob/b185fb5ff3c985402ab2e6f0e537066be48fb8bb/src/integrations/corda/main/utils/network/corda.js#L271-L274

**Comment by tcoulter** [comment]
From David: Error message sticky no matter which screen?

**Comment by tcoulter** [comment]
Alright, I have good news and bad news. 

The good news is, I've isolated the issue! 🎉 The bad news is there's a much larger issue with error handling in `src/main/index.js`. 👎 

To start, it looks like someone has built a significant error handling system that passes errors from the backend to the frontend. It's pretty clear that whoever wrote it was trying to make our lives easier by creating a way to trigger user interface actions by setting attributes on the error object itself. For instance, see [this example](https://github.com/trufflesuite/ganache/blob/feat/corda/static/node/truffle-integration/projectDetails.js#L172). This error will be passed on through the backend pipes until it's serialized and passed on to the frontend, where the frontend will then process it [here](https://github.com/trufflesuite/ganache/blob/feat/corda/src/renderer/init/ErrorHandler.js#L18) and perform an appropriate action. Once you understand that the system is built this way, it's actually really simple to create errors that trigger the config screens to pop up.

But, there's a bigger issue.

It turns out that a significant amount of error handling within `src/main/index.js` is relying very heavily on the `uncaughtException` and the `unhandledRejection` handlers defined at the top of the file. For instance, see the `startServer()` call [here](https://github.com/trufflesuite/ganache/blob/feat/corda/src/main/index.js#L489). This is the function that fails when a port is already in use, triggering a bunch of promise rejections deep in the corda underbelly that ultimately bubble back up to this line. There's no explicit error handling here, as this code's hanging out in some async IPC event handler, so the `unhandledRejection` handler at the top of the file picks it up and sends it to the frontend.

Why is this an issue? For starters it threw me for a loop for quite some time. But secondly, it appears these handlers weren't built to be a main thoroughfare for error handling. As it turns out, these handlers convert the error objects to strings via `err.stack` and *completely bypass the clever error handling system* mentioned above. It doesn't matter if you've flagged your error as a `PROJECTERROR`, that data gets wiped clean in the conversion. 

We can easily remove the `err.stack` preference as a main thoroughfare, but I don't think we should. These uncaught exception handlers were meant to be safety nets and not your main error handling mechanism (as I'm sure you know). To fix this completely, I'd add explicit error handling for all the potential promise rejections throughout the backend's lifecycle. 

Here are some other places in that file where errors are likely getting sent through these handlers: 

* [here]()
* [here]()

To your question of why the current Ethereum implementation can handle these errors and Corda can't, 
I'm sure you know this, but those handlers are meant to be a safety net in case something was missed, and not a main thoroughfare. As written, those handlers convert the error object into a string, which then completely negates the clever error system the person above wrote. 

I'd imaging

**Comment by tcoulter** [comment]
Accidently clicked comment before I was done. I significantly edited the comment above. ☝️

**Comment by davidmurdoch** [comment]
Thanks for digging, @tcoulter! I'm okay with leaving these unhandled promise rejections, as I'd prefer that the functions being called handle internal exceptions as far as they can, without rejecting; bubbling up to the main/index.js handler should be reserved for truly exceptional circumstances, as you've mentioned.

So, I don't think we need to patch all of these uncaught `await`s.

For the class of errors we are trying to handle (Corda port-bind errors, and other configuration-related failures), that `integrations.on("error", ...)` method that `pojoify`s the error ([here](https://github.com/trufflesuite/ganache/blob/162bed09268ad62ab0badbdcc08f98255aa6573e/src/main/index.js#L370)) is probably pretty trivial to trigger from the Corda start-up pipeline:

In https://github.com/trufflesuite/ganache/blob/b185fb5ff3c985402ab2e6f0e537066be48fb8bb/src/integrations/corda/main/utils/network/manager.js#L248-L252

...instead of `throw e;` I _think_ we can just do a `this._io.sendError(e); return;` here, which will not trigger the top-level `unhandledPromiseRejection` handler, and will trigger the `integrations.on("error", ...)` handler instead, successfully `pojoify`ing the error message. It's likely not _quite_ this easy, but I think it'll be the best place to start.

To answer directly:

 * let's leave those other `await`s as they are.
 * I'm wary of possible unknown side-effects of removing the `err.stack` parts of the `uncaughtException` and `unhandledRejection` handlers. Do you thinking `pojoify`ing these could cause problems? If not, let's update them!
 * Even if we update the `uncaughtException` and `unhandledRejection` rejection handlers, I'm thinking triggering the `integrations.on("error", ...)` handler explicitly, in the way I've described above, is the correct approach for these Corda configuration errors.

_note: in [my comment above](https://github.com/trufflesuite/ganache/issues/1560#issuecomment-604021330) I had linked to the wrong `catch` block; it should have linked to [these lines](https://github.com/trufflesuite/ganache/blob/b185fb5ff3c985402ab2e6f0e537066be48fb8bb/src/integrations/corda/main/utils/network/manager.js#L248-L252) instead, sorry!_
