### ISSUE TITLE
Warn about number of machine resources that will be used

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1576]
There is no warning about the number of computing resources that a default configuration will take.

## Expected Behavior
Indication on the expected computing resources required. Ideally checking the available resources and warning when not enough are available, implying some applications may need to be closed before running a default configuration/workspace.

## Current Behavior
The configuration starts, potentially freezing/pausing other running applications without warning.

## Steps to Reproduce (for bugs)
Just start a configuration where the host has many other applications running (e.g., MS Word, Powerpoint, Excel, Chrome with many tabs, Mail, etc. that are consuming more resources than the Corda configuration is expected to consume.

## Context
Many apps were locked up after launching the Ganache workspace.

## Your Environment
MacOS

**Comment by davidmurdoch** [comment]
We're considering _attempting_ to mitigate some of these start-up woes via https://github.com/facebook/nailgun, but I'm not too hopeful it will even work, let alone solve the extended 100% CPU usage issue.

Workspaces _should_ always be able to run as long as the system has enough disk space available (and their OS settings haven't been configured to disallow the use of swap). Eventually Corda will finish starting up and the CPU use will return to idle.

Having users to close other running applications will not solve the issue or decrease start up time by any significant amount.

On Windows and Linux we may be able to set the processor affinity to mitigate the issue, but on Mac I'm not aware of a way to limit a process's CPU use (without requiring a properly configured Docker instance).

I do think adding a warning message to the Start UI for Corda networks that their system may become unresponsive while the network is starting is a great idea. I'd also like to add a "Cancel" button to the loading screen so the user can abort start up without having to force quit (though if their OS is locked up, this idea may not actually work in that case).

note: the reason we don't use Docker already is because doing so would require the users install complicated prerequisites before using corda-flavored Ganache UI -- which has always been a goal of ours -- Ganache UI's target demographic includes users who are not tech-savvy enough to install something like Docker (maybe it's easy on Mac, but on Windows and Linux it is not).
