### ISSUE TITLE
Why not use H2 vs Postgres?

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1577]
Seems like the start up might be quicker if it just used the embedded H2. Was there a design reason for choosing Postgres for a development environment running on a local machine?

## Expected Behavior
Quick start up with minimal machine resource consumption.

## Current Behavior
Postgres is downloaded and configured to run with Corda

## Possible Solution
Use H2.

## Steps to Reproduce (for bugs)
Initial launch of Ganache with Corda workspace.

## Context
There may be a good reason why Postgres was selected. Not sure, but if H2 is sufficient it reduce the need to download more resources to the machine. 

## Your Environment
MacOS

**Comment by davidmurdoch** [comment]
Hey @guyho. I'm currently on vacation and won't be back in until the around 7th, but I just wanted to come on here and say thank you for taking the time to open all these issues!

We went with postgres because we were consulted by R3 that postgres is more reliable than H2, especially when it comes to persistence, which we require.

As far as the initial start up time goes, this is likely due to the way we are currently downloading the assets. For some reason it seems that on Mac it downloads/extracts these "extras" files (postgres, jre, corda-bootstrapper, blob-inspector) sequentially. We haven't yet done _any_ performance work yet, but improving initial startup time is high on the list.
