### ISSUE TITLE
The private key is not prefixed with a "0x" when shown

### ISSUE THREAD

**Issue by critesjosh** [trufflesuite/ganache#1608]
## Expected Behavior
When I copy the private key from Ganache GUI, I don't want to have to add the "0x"

## Current Behavior
When I copy the private key from Ganache GUI as is and try to sign messages with it using web3.js, it is not a valid signature.

## Possible Solution
Add "0x" to the beginning of the private key string that is displayed.

## Steps to Reproduce (for bugs)
1. Open Ganache GUI and start
2. From the main accounts page, click "show keys"
3. See that private keys are not prefixed with "0x"

![image](https://user-images.githubusercontent.com/18372439/73376682-d5054080-428b-11ea-8e2b-f4963ca52420.png)

## Context
When I copy the private key from Ganache GUI as is and try to sign messages with it using web3.js, it is not a valid signature when trying recover using ecrecover in Solidity.

**Comment by davidmurdoch** [comment]
This format imitates MetaMask's private key export UI, which doesn't prefix the string with `0x`. Also, MetaMask's import UI requires a prefixless private key, and because it masks the pasted private key with `*`'s I prefer to keep Ganache's private keys as-is, so it works in meta mask without the user having to wonder what's wrong.

If you would like to submit a PR adding this as a feature you can toggle in the Advanced config (something like `Prefix Private Key with "0x" in Account Information`) I'd gladly pull it in!
