### ISSUE TITLE
Take Snapshot

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/ganache#26]
What does `Take Snapshot` feature do?

**Comment by johnmcdowall** [comment]
It allows you to take a snapshot of the chain at the current time, and later revert back to it.

**Comment by peterphan1996** [comment]
@seesemichaelj thank you, but I just want the `resume` feature like ganache-cli with --db flag

**Comment by seesemichaelj** [comment]
Ah, that's different than snapshotting. Snapshot is the ability to go back to a prior chain state.

It sounds like you want to load existing chaindata instead of starting with a fresh chain each time.

In the upcoming Ganache UI 2.0 release, you'll be able to create workspaces which use persistent chains.

**Comment by peterphan1996** [comment]
Thank you for pointing that one out for me. I thought the taking snapshot feature is like that one i mentioned, silly me.
