### ISSUE TITLE
Windows 7 cannot install appx

### ISSUE THREAD

**Issue by KekvinFu** [trufflesuite/ganache#295]
who know how to install appx in windows 7 ? I download and install powershell 4.0, but when install appx, it told me the command add-appxpackage is not supported.

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by KekvinFu** [comment]
who know how to install appx in windows 7 ? I download and install powershell 4.0, but when install appx, it told me the command add-appxpackage is not supported.

**Comment by benjamincburns** [comment]
Hi @KekvinFu. Unfortunately appx files aren't supported in Windows 7. We're looking into producing an MSI file which _should_ be able to run on older versions of Windows, however Windows 10 is the only supported version at this time.

**Comment by snarun** [comment]
Yes, An MSI would be helpful. Are there any time frame set for this?

**Comment by benjamincburns** [comment]
There isn't, sorry.

If you'd like to raise a new issue for that and submit a PR, I'd be much obliged. I think you can start by adding `squirrel` to the list of `electron-package` targets in `package.json`. You'll have to read the electron-forge and electron-package docs for more info than that, however, as I haven't really dug into it yet.

**Comment by benjamincburns** [comment]
@KekvinFu & @snarun - sorry - I forgot to mention that you should still be able to clone and build locally...

If you want a one-liner for that, `git clone git@github.com:/trufflesuite/ganache; cd ganache; npm install -g windows-build-tools; npm install; npm start` ought to do it.

**Comment by moustaphaba** [comment]
Dear @benjamincburns, Dear superpikar 
i have tried to use the cloning approach because i work with windows 7. Anyway, whenever i do the first command  "git clone git@github.com:/trufflesuite/ganache" it says me 
git@github.com:  permission denied (publickey)
Fatal: could not read from repository
Pleas e make sure you are the correct access rights and the repository exists. 

I need a help, please....

Best regards,

**Comment by moustaphaba** [comment]
Dear @superpikar 
i have tried to use the cloning approach because i work with windows 7. Anyway, whenever i do the first command  "git clone git@github.com:/trufflesuite/ganache" it says me 
git@github.com:  permission denied (publickey)
Fatal: could not read from repository
Pleas e make sure you are the correct access rights and the repository exists. 

I need a help, please....

Best regards,

**Comment by davidmurdoch** [comment]
@moustaphaba, have you tried using an `exe` from the [Releases](https://github.com/trufflesuite/ganache/releases/) tab?

**Comment by moustaphaba** [comment]
@davidmurdoch 
yes i have tried the beta.2-setup.exe. It does not work because require 64 bites.

 i have tried also he beta.2.appx for windows (under recommandation) but i dont know how to open and install the .exe. 

Do you have idea ?  how to install the file.appx ? may be it will be more easy for me. 
best,

**Comment by seesemichaelj** [comment]
@moustaphaba To get ganache working on a 32bit Windows 7, you'll need to clone and build yourself like @benjamincburns mentioned.

However the command provided is for us maintainers and not for the community at large. I have modified the command below:
`git clone https://github.com/trufflesuite/ganache; cd ganache; npm install -g windows-build-tools; npm install; npm start`


That's the one-liner command. but if you have problems along the way, but you can try executing them one at a time:
- `git clone git@github.com:/trufflesuite/ganache`
- `cd ganache`
- `npm install -g windows-build-tools`
- `npm install`
- `npm start`

**Comment by seesemichaelj** [comment]
@moustaphaba, @davidmurdoch mentioned to me that the `npm install -g windows-build-tools` may need to be executed as an Administrator. You may also need to run it under Powershell instead of the Command Prompt if you have issues with Command Prompt. [Here](https://www.isunshare.com/windows-7/run-command-prompt-as-administrator-in-windows-7.html) is a tutorial on how to run command prompt as an Admin

**Comment by moustaphaba** [comment]
Al the instructions work instead   "npm install"   see the two capture image
![capture_error1](https://user-images.githubusercontent.com/20513144/51559689-dc2c8e00-1e82-11e9-9aae-faa8acf43143.PNG)
![capture_error1](https://user-images.githubusercontent.com/20513144/51559715-f1a1b800-1e82-11e9-9d41-089e169a97e9.PNG)

**Comment by moustaphaba** [comment]
at the end of GIT CMD  you can see this : 
![capture_error2](https://user-images.githubusercontent.com/20513144/51559854-5826d600-1e83-11e9-9547-145badc73390.PNG)

**Comment by moustaphaba** [comment]
@seesemichaelj  thak you.  But can you see my two last answer please ?  :(

**Comment by seesemichaelj** [comment]
@moustaphaba was the `npm install -g windows-build-tools` command successful? That command must be successful for `npm install` to work.

**Comment by moustaphaba** [comment]
@seesemichaelj 

yes it works

**Comment by moustaphaba** [comment]
@seesemichaelj 
but the followin       npm install 
des not work.  see the two pictures below

**Comment by seesemichaelj** [comment]
@moustaphaba looks like there is an error in https://user-images.githubusercontent.com/20513144/51559715-f1a1b800-1e82-11e9-9d41-089e169a97e9.PNG

which indicates you need to manually install `libvips` and to see https://sharp.dimens.io/page/install

on there it says
>For 32-bit Intel CPUs and older Linux-based operating systems such as Centos 6, compiling libvips from source is recommended.

with the link https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

I'm not sure how easy this is, etc. but perhaps those are the next steps?

**Comment by moustaphaba** [comment]
@seesemichaelj 
@benjamincburns 

I see the problem when i use "powershell" instead "invites de command" for the commands  
cd ganache
npm install -g windows-build-tools
npm install

it says me "no git binary found in PATH" .

Indeed GitHub for Windows does install its own version of Git, but it doesn't add it to the PATH variable. 
I think. I will come soon when all is ok. or...not :(  
See you soon, thank

**Comment by moustaphaba** [comment]
@seesemichaelj 
@benjamincburns 
see a screem shot of my installation. what is my PATH ? helpe

![git_path](https://user-images.githubusercontent.com/20513144/51603716-e09c8980-1f0a-11e9-81d8-dd60afd654ed.PNG)
