### ISSUE TITLE
testcase pass on 1.0.2, but fail on 1.1.0-beta.0

### ISSUE THREAD

**Issue by leochan007** [trufflesuite/ganache#308]
some cases need exception thrown when testing.
on 1.0.2 it is ok.
but on 1.1.0-beta.0 the expected except was never thrown.

**Comment by benjamincburns** [comment]
Hi @leochan007. Sorry for the confusion, but this is expected behavior. I'd encourage you to please reread the release notes. In particular, the section about error handling.

We'll be publishing a new beta in the next few days which exposes a switch in the settings which lets you toggle this behavior on and off.
