### ISSUE TITLE
New official Ganache breaks error catching

### ISSUE THREAD

**Issue by nickjm** [trufflesuite/ganache#315]
When I upgraded Ganache to the new official version from the site (1.1.0-beta.0) Some of my error catching stopped working as expected. For example, the defacto error handling below, taken from truffle & ganache examples:
```
try {
  await promise; // some generic transaction with a contract that should fail via revert or require.
} catch (error) {
  const revertEvent = error.message.search('revert') >= 0;
  assert(revertEvent, 'expected revert');
}
```
This will no longer work. An error is not thrown, and instead the txn receipt includes a status of 0. This is problematic because I'm now unsure how to check for reverts vs. invalid opcodes, etc. It would be nice if this information was somewhere in the documentation or on the site, or at least on the github there was a guide for how to update after these breaking changes / new recommended standards for things like error checking. I understand this is also a beta version BUT when a heartbeat issue came up with 1.0.1 I was told I had to update to fix the issue or even get help. Additionally, this beta is the official version on the ganache site.

## Expected Behavior

Web3 0.1 behavior txn receipts and errors thrown in javascript when transaction fails OR some new way of detecting types of errors besides the 0/1 status in a web3 0.2 receipt

## Current Behavior

An error is not thrown on a revert, invalid opcode, invalid jump or any other EVM error.

## Possible Solution

Either change whatever in Ganache affects version of web3 to support old behavior temporarily (preferred because web3 0.2 doesn't even seem to be at the official release stage. Or include info on how to fix breaking changes.

## Context

I'm trying to run transactions that throw different types of errors, e.g. reverts and invalid opcodes, and validate that the correct errors were thrown.

* Version used: 1.1.0-beta.0
* Operating System and version: MacOS 10.13.3 High Sierra

**Comment by benjamincburns** [comment]
Hi @nickjm. Rather than leaving a lengthy comment here, can you please go and read ["Important note about contract runtime error reporting"](https://github.com/trufflesuite/ganache-cli/releases/v7.0.0-beta.0)? We linked to this from the [Ganache beta release notes](https://github.com/trufflesuite/ganache/releases/tag/v1.1.0-beta.0) (look for the bold bullet point titled "Important").

Note that in the next beta there will be a toggle switch in the settings for enabling/disabling this functionality.

> This is problematic because I'm now unsure how to check for reverts vs. invalid opcodes, etc.

Unfortunately this is the way that production clients work. As a result, it's best practice to write your tests such that they handle this situation. If you're using `truffle-contract`, there's a PR in progress now (or just recently merged, maybe?) which checks the receipt and throws on `status == 0` like you're asking for here.

**Comment by nickjm** [comment]
thanks!
