### ISSUE TITLE
Batch request only returns first response

### ISSUE THREAD

**Issue by AndyQ** [trufflesuite/ganache#320]
Using MyEtherWallet, trying to deploy a new contract, clicking the Sign Contract button does nothing (except for a "Possibly unhandled rejection error in the console).

The reason is that MyEtherWallet sends a request for 3 transactions:
eth_getBalance, eth_gasPrice, and eth_getTransactionCount

However, latest beta Ganache only returns the response for the first request.
Note - the previous version 1.0.2 returned all three responses.

**Request sent:**

**Host:** 
```
http://127.0.0.1:7545
```
**HTTPHeaders:**  
```
Content-Type = application/json; charset=UTF-8
```

**Request body:**
```
[
  {
    "id" : "cb2ae8248d3cb6e69968fde7b12f3036",
    "jsonrpc" : "2.0",
    "method" : "eth_getBalance",
    "params" : [
      "0x627306090abab3a6e1400e9345bc60c78a8bef57",
      "pending"
    ]
  },
  {
    "id" : "2c1c0a654640a15468c7253b5167b9ca",
    "jsonrpc" : "2.0",
    "method" : "eth_gasPrice",
    "params" : [

    ]
  },
  {
    "id" : "577e6a7e5615d9f667cd0a895921ae5a",
    "jsonrpc" : "2.0",
    "method" : "eth_getTransactionCount",
    "params" : [
      "0x627306090abab3a6e1400e9345bc60c78a8bef57",
      "pending"
    ]
  }
]
```

**Response (from 1.1.0-beta1):**
```
[
  {
    "id" : "cb2ae8248d3cb6e69968fde7b12f3036",
    "jsonrpc" : "2.0",
    "result" : "0x56bc6ecd9c1e7a800"
  }
]

```

**Response (from 1.02):**
```
[
  {
    "id" : "cb2ae8248d3cb6e69968fde7b12f3036",
    "jsonrpc" : "2.0",
    "result" : "0x00000000000000056bc75e2d63100000"
  },
  {
    "id" : "2c1c0a654640a15468c7253b5167b9ca",
    "jsonrpc" : "2.0",
    "result" : "0x4A817C800"
  },
  {
    "id" : "577e6a7e5615d9f667cd0a895921ae5a",
    "jsonrpc" : "2.0",
    "result" : "0x0"
  }
]
```

**Comment by galante** [comment]
I’m having the same issue, I’m going to rollback to 1.0.2.

**Comment by phbernard** [comment]
As an aside, this issue is triggered when following [this tutorial](https://medium.com/crypto-currently/build-your-first-smart-contract-fc36a8ff50ca) published on Medium. The article itself has been applauded 2.3K times and the top comment is about this issue and has been applauded 44 times.

I have no idea if this issue is often annoying, but at least be aware that several newcomers might encounter it.

**Comment by benjamincburns** [comment]
Thanks for the link @phbernard.

@AndyQ one small issue with the request you posted above, the `id` field should be a JSON number, not a string.

Otherwise, I've reproduced this bug. It seems our batch request processing is broken. If I run the requests independently it seems we respond correctly. I'll get this fixed up now so it'll go out with the next beta release.

**Comment by benjamincburns** [comment]
Fixed in `develop` branch of `ganache-core`. Will be included in the next beta of the Ganache UI as well as ganache-cli.

Thanks for reporting this, everyone!
