### ISSUE TITLE
Add Support for RPC CORS

### ISSUE THREAD

**Issue by jacktang** [trufflesuite/ganache#359]
Hello, 

Now ganache does not provide address searching, and can I use eth explorer(https://github.com/carsenk/explorer) and let it connect to ganache?

**Comment by seesemichaelj** [comment]
I don't believe Ganache currently supports RPC CORS which looks like a requirement for your eth explorer. This will definitely be a low priority, but we're open for pull requests! If someone wants to work this, please comment on this issue before you get started so we can talk plan of attack.

**Comment by dinostabOMG** [comment]
Possibly related: when trying to connect in browser through web3, Firefox will not accept the request and returns this error: 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:7545/. (Reason: missing token ‘user-agent’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).`

Chrome doesn't disallow connection for this reason, so that is a workaround. However if it would take only the header token to make this work, it seems like it could be useful. I'm a bit new to the related issues but I would be willing to take a whack at fixing this and making a pull request, @seesemichaelj .

**Comment by seesemichaelj** [comment]
@dinostabOMG If you want to take a stab at it, that'd be great! I'm not quite sure how deep this rabbit hole may go. Let me know if you end up giving up for whatever reason so I can know that you're no longer working it.

Thanks!

**Comment by dinostabOMG** [comment]
Thanks. Did you want to talk plan of attack kind of stuff? It would be useful to be pointed at where RPC requests are handled, I think.

**Comment by dinostabOMG** [comment]
Is it not in this repo? It looks like what we're after is here:

https://github.com/trufflesuite/ganache-core/blob/develop/lib/httpServer.js

Still sussing out the relationship between the repos `ganache`, `ganache-core`, and `ganache-cli`, though.

**Comment by dinostabOMG** [comment]
Thanks @davidmurdoch . This is in reference to the same issue, but as pointed out in that thread, it isn't a bug in web3.js, it's a missing response header from the server application. Which in our case, is ganache (or perhaps ganache-core?)

Arguably, you could say that Firefox should not request the User-Agent header - and I'm not sure why it makes that request with the webpacked version but not the minified version. But in either case, we could solve the problem by sending the header, if I understand correctly.

**Comment by benjamincburns** [comment]
@dinostabOMG Thanks for looking into this!

We're going to try and cut a release of the full ganache suite on Monday evening or Tuesday morning PDT. I'd love to include your PR in that, but no pressure if you don't make it in time.

In the mean time a PR for this would be perfect if by default it allowed access from any referral domain but also added support for a string `corsdomain` field to our `options` object which at a minimum would respond to the CORS preflight with an `Access-Control-Allow-Origin` value that matches whatever the user sets.

We'd likely accept a PR without that, but if we were doing it ourselves that'd be how we'd go about it.

Also please be sure to include a test so that we don't regress on this feature!

**Comment by dinostabOMG** [comment]
While investigating, I learned that I glommed onto the wrong issue with my above comment about Firefox. However, _that_ problem was a very simple fix to `ganache-core`, reflected in [this PR](https://github.com/trufflesuite/ganache-core/pull/142/commits/fb174a44ac26e86fe486d644d2372b70921a8a60)

I'll do a separate pull request for affecting domain control when I get that figured out... dunno if it will be before the next release unfortunately, since that's quite tight.

**Comment by seesemichaelj** [comment]
Closing via https://github.com/trufflesuite/ganache-core/pull/142

**Comment by dinostabOMG** [comment]
Does this actually resolve the issue as reported though? There's still no option to restrict CORS to specified domains as Benjamin requested. My PR only adds one header that Firefox requested.

**Comment by seesemichaelj** [comment]
CC @davidmurdoch :point_up:

**Comment by davidmurdoch** [comment]
@dinostabOMG, you're correct. We've opened https://github.com/trufflesuite/ganache-core/issues/143 to finish out the `access-control-request-headers` feature and we'll be tracking the custom CORS domain enhancement in https://github.com/trufflesuite/ganache-core/issues/150
