### ISSUE TITLE
System Error when running Ganache 1.1.0-beta.1 on linux

### ISSUE THREAD

**Issue by Xtchen** [trufflesuite/ganache#366]
PLATFORM: linux
GANACHE VERSION: 1.1.0-beta.1

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

FWIW, the error was seen during the first time launch. After relaunching, it seems to be working well.

**Comment by benjamincburns** [comment]
Thanks for reporting this, @Xtchen.

We'll be adding some better UI/UX to handle network errors soon. In the mean time, if the problem is transient, it was probably environment-specific and there's not much we can do. However, if you find this is happening every time you start up Ganache and you're sure nothing else is listening on that port, please come back and reopen this issue!
