### ISSUE TITLE
Question - does it possible to programatically restart Ganache & reset accounts balances?

### ISSUE THREAD

**Issue by zulhfreelancer** [trufflesuite/ganache#370]
## Summary

I'm using Truffle & Ganache to test my contracts using JS. I'm curious to know whether if it's possible to restart Ganache & reset the accounts balances before the tests start.

## Context

I have quite a lot of contracts to be tested. Since I'm using Ganache and each accounts only have 100 ETH balance, sometimes I didn't notice that some of the accounts already reach their zero (0) ETH balance and I need to restart the Ganache manually to reset back the balances to 100 ETH.

Plus, I think it will be much more cleaner for me to run the tests with a 'clean network' state rather re-run the tests with some accounts have <100 ETH balances and with previous tests' transactions & blocks.

I also looked at [ganache-cli](https://github.com/trufflesuite/ganache-cli) as another option. But, I need 2 terminals for that; 1 running ganache-cli and another 1 running the `truffle test` command which is not what I want. I'm looking for 2-in-1 solution where I can do the following in just one command i.e. `truffle test`:

**Start ---------------------------------------------------------------------**

1. Restart Ganache (and reset all account balances, blocks & transactions)
2. Run all the tests (`truffle test ...`)

**End ----------------------------------------------------------------------**

## Environment
* Version used: 1.1.0-beta.0 (1.1.0-beta.0)
* Operating System and version: macos Sierra 10.12.6

**Comment by benjamincburns** [comment]
Hi @zulhfreelancer,

I'm afraid it's unlikely that we'll add this feature the the Ganache UI, as it's meant to be more of a development tool than a tool used for automated testing. For example, how would you set up Travis CI for tests like this? This is why we keep `ganache-cli` around.

Regarding a "clean network", truffle is meant to `evm_snapshot` and `evm_revert` after each `contract` directive in your JS tests, and after each solidity test contract. At the moment there's an off-by-one bug in truffle test (trufflesuite/truffle#710) which causes it to not revert on the last contract in your suite, so you may be running afoul of this. However, if it's not reverting the state of the chain at all, then I'm guessing that you're likely using `describe` in your tests instead of `contract`.

Regarding running out of ETH, see `ganache-cli --help`. You can use the `-e` or `--defaultBalanceEther` flag to set the initial balance of the accounts ganache generates for you.

Finally, you don't need to open two consoles open when using `ganache-cli`. Thanks to bash, you can always run `ganache-cli` as a background process by adding an ampersand at the end of the command. This will still cause it's stdout to be written to your terminal, which may get annoying, so I'd recommend redirecting its output to a file like this:

`ganache-cli 2>&1 > ganache-output.log &`

Running this will give some output like `[1] 12345`, where `1` is what's known as the "job number" and `12345` is the pid. If you type `jobs` you'll see 
`[1]+  Running                 ganache-cli 2>&1 > ganache-output.log &`

And if you type `fg 1` you'll bring job 1 into the foreground. To background it again (or any other active program in bash), hit ctrl-z, then run `bg 1`, or whatever its job number is. You need the `bg` command because hitting `ctrl-z` actually suspends the program, pausing its execution. `bg` tells it to keep running, but in the background.

If you want to view ganache's output, you can open `ganache-output.log` in your favorite text editor. And if you decide later on that you want to be able to watch the output while it's running, you can still open another console and do `tail -f ganache-output.log` to watch the file as it updates.

Finally, when you're done, you can use `kill 12345` or whatever the PID was to terminate `ganache-cli`, or you can just `fg 1` and hit ctrl-c.

HTH!

**Comment by benjamincburns** [comment]
One last tip, if you're doing multiple automated test runs and you want a log file for each run, use a timestamped log filename like so:

`ganache-cli 2>&1 > ganache-output-$(date +%Y-%M-%dT%H:%M:%S).txt &`

See `man strftime` if you want to customize the timestamp format.

**Comment by zulhfreelancer** [comment]
Thank you @benjamincburns. Really appreciate it!

**Comment by n13** [comment]
I am setting the timestamp on the chain using increaseTimeTo - and it's definitely not reverting that. 

The test depends on blocktime so in order to run it automated, I have to constantly restart the cli

Also it seems there's no way to set an initial date either, so if my computer current time is > my increaseTimeTo time, the automated tests will no longer work

**Comment by n13** [comment]
No, didn't find a workaround. I'd shuffle the tests around so the evm time is constantly increasing. Not a good solution, and still need to restart the cli between test runs.

**Comment by Zergity** [comment]
Here is how I get it done on Linux:
```
fuser -k -n tcp 8545; ganache-cli --time $SOMEDATE & truffle test
```
8545 is the port that ganache-cli listens on
