### ISSUE TITLE
Can't Open Ganache 1.0.2 on Linux, please help!

### ISSUE THREAD

**Issue by ericliyanghui** [trufflesuite/ganache#460]
## Problem Description:
Several days ago, to develop the project based on Ethereum, I installed ganache-1.0.1 for linux and ran correctly with GUI shown. However, after I closed my computer and start it again today, I cannot open it with the interface shown.
The screenshot is as follows:
![2018-03-25 17-41-44](https://user-images.githubusercontent.com/35229624/37873660-d8d3bd46-3053-11e8-9ff6-6df89cb8d608.png)

## Possible Solution
1. At the beginning, I suspected that it was the problem of version so I updated it to ganache 1.0.2, but the result is the same.
2. Another one is that because my computer is dual system for both Windows 10 and Ubuntu 16.04. But I never used Win10 before. Just the day before yesterday, when I opened computer, it started automatically from Windows boot and I cannot enter linux. But after I closed "Secure Boot" it recovered. I don't know if it affects something.

## Context
Ganache is one of the most important part of developing Dapp. If I can't use it, I cannot continue.

## Your Environment
* Version used: ganache-1.0.2-x86_64.AppImage
* Operating System and version: Ubuntu 16.04

**Comment by seesemichaelj** [comment]
Hi @ericliyanghui, thanks for reporting this! I'm so sorry that we haven't been able to get to this issue until now!

I'm not familiar with the error you're having.
- Have you given your file execution privileges (I'm assuming so, because it looks like the terminal let you execute it)? (i.e. `chmod a+x ganache-1.0.2-x86_x64.AppImage`)
- Are you using a 64 bit OS?
- Have you tried the latest release (1.1.0)? https://github.com/trufflesuite/ganache/releases/tag/v1.1.0

**Comment by seesemichaelj** [comment]
I am now familiar with this issue, and I can confirm that adding execute permissions on the `AppImage` should work. The output on this screen is not an error per-se. It's also possible there is another window open but not focused asking if you'd like to add desktop/start menu icons for Ganache.
