### ISSUE TITLE
Where is configuration file?

### ISSUE THREAD

**Issue by askucher** [trufflesuite/ganache#519]
Hello guys,

I do not have time to read all this info here but 

1. I have installed Ganache GUI to save time. 
2. Changed network settings. The pointed ganache on a remote server. 
3. Remove server is gone
4. Opening a ganache and cannot change the network setting (Endless welcome screen)

**Comment by benjamincburns** [comment]
@askucher did you ask in [gitter](https://gitter.im/ConsenSys/truffle)?

**Comment by benjamincburns** [comment]
We use `electron-settings` for configuration. Please refer to the documentation for `electron-settings` to determine where the file is located on your OS.

You can't point Ganache at a remote server. If you specify a remote host, Ganache's internal blockchain will attempt to open a socket listening on that host. Since that host doesn't exist on your machine, the underlying blockchain process dies. Since you're reporting that it hangs on start, I assume you're not using the latest version (1.1.0).
