### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by mmezian** [trufflesuite/ganache#531]
## Expected Behavior
When migrating (or using truffle test, which is what I do all the time), should execute the compilation, migration, and launch tests

## Current Behavior
Every 3-5 migrations, ganache crashes  with the following code : 

Blockchain process exited prematurely with code '7', due to signal 'null'.

## Possible Solution
No idea, i think your migration contracts is causing this

## Steps to Reproduce (for bugs)
I suppose this problem is common? what is the solution? 

## Your Environment
PLATFORM: win32
GANACHE VERSION: 1.0.2
Node : v 9.5

**Comment by mmezian** [comment]
Just pointing out that 3-4 times at of 5, it works perfectly

**Comment by seesemichaelj** [comment]
Thanks for reporting this!

Unfortunately, I'm not sure which issue to triage this under due to missing the extra application logs.

It is highly likely this issue will be under #667, #668, #669, #413, #616, #362, or #443. I'm going to close this as the error provided is unfortunately generic and hope it's covered in one of those issues. Please feel free to submit these issues however! We'll triage them into the correct issue if it already exists.

Thanks again!
