### ISSUE TITLE
Appx is suggested for windows instead of exe

### ISSUE THREAD

**Issue by Gargo** [trufflesuite/ganache#550]
spent a lot of time to find out how to install it for windows - no one of suggested methods work. Finally found out that you have normal exe files but they are hidden here.
What about to mention existing exe files somewhere on main website?

**Comment by seesemichaelj** [comment]
Hey @Gargo, so sorry for the delay here. We got behind on addressing Github issues and trying to catch up. Thanks for being patient!

I'm going to discuss this with the other devs about making this easier!

**Comment by mokeychan** [comment]
so how to install Appx on Windows7！

**Comment by seesemichaelj** [comment]
The website will shortly (once autodeployment finishes) start serving the EXE file for OS versions < Windows 8

**Comment by mokeychan** [comment]
Thanks for you help! I forgoted to say that l have solved this problem by npm moudle.

**Comment by seesemichaelj** [comment]
@mokeychan no problem! I'm **trying desperately** to address these Github issues. I'm curious what you mean by `npm module`. `Ganache`, this repo, is a GUI interface to `ganache-cli` (which is a wrapper around `ganache-core`). Sounds like you just installed `ganache-cli` globally via `npm` to instantiate a chain. With that said, don't be afraid of using the GUI. While more options are available in `ganache-cli`, we're constantly working to improve the GUI interface as it is more user friendly.

Cheers! :clinking_glasses:

**Comment by Gargo** [comment]
@seesemichaelj and?  for example I have Windows 10 but I don't have built-in windows market and it is a big problem for me to install this market without of reinstalling the windows. And I don't know in general why do you prefer appx. Why not to mention it on the main website? I visit your website for a first time then I need to know somehow that you have the installer I need but I must to search it on github, don't I?

**Comment by seesemichaelj** [comment]
@Gargo Thanks for the continuous feedback! Active community is really important to us (probably more than it appears, but we're trying to enhance that!!).

I wasn't aware of the built-in windows market limitation to installing appx files. I'll go test and verify that and that'll help us make our final decisions.

#### RE: Not knowing about github releases
With that said, I totally understand you and working the angles to get it approved to change the website to be more intuitive and user friendly. I agree with you that the verbiage doesn't let the user know that there is another Windows download available.

We're likely going to change the website tomorrow to say something like "Download Another Version" instead of "Need a different OS download?" to help users in your situation realize the link will provide you other install media. **Please answer:** do you think this change would be sufficient for users to be "oh...I guess this doesn't work..oh! there are other versions, let's check that!"?

#### RE: preferring the appx:
Several months ago, the exe installer was horrendous and difficult to get working on some Windows 10 setups; one of our devs thus added support for the appx installer which worked a lot better. Since then, the exe installer has been revamped to be more normal/standard to prevent user frustration. The website just hasn't been updated until now because of the very concerns you presented :)

I can't promise one thing or another, but we're in active discussion about pros/cons one way or another. I'll reopen this issue until the wording changes as that was your original concern (which I initially misinterpreted) to just tell users about the Github page.

### Thanks!
Thanks for the feedback, it really helps.

**Comment by seesemichaelj** [comment]
We're now using the wording `Choose a different version` as the link underneath the download button. This should convey the existence of other available downloads.

https://github.com/trufflesuite/trufflesuite.com/commit/5ac04c87bcf002898733a3acd9127c19bd3fd891 fixes this
