### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by lbrth** [trufflesuite/ganache#596]
I have this bug to day, I don't know how its appear exactly. I restarted Ganach but nothing change.

Thank's in advance for the help,

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":100,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #665. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.

**Comment by seesemichaelj** [comment]
@lbrth you can checkout the workaround instructions I recently added in #665. We're working on a better way to allow you to change the settings when the error happens.

It's possible this happened either due to multiple instances of Ganache running, or a crash happened causing the port to not be unbound. Simply changing the settings to use another port should get you running again.
