### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by yojeon** [trufflesuite/ganache#749]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"localhost","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this!

Looks like `localhost` is not a valid hostname. Please either add it to hosts file (https://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want) or use `127.0.0.1`

You can change your settings file at `~/Library/Application\ Support/Ganache/Settings`

We'll be releasing a new version soon with a better way to change your settings on these kinds of errors (see #665 and #666) as well as a change in how the hostname is selected (using a dropdown instead of a text box)
