### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by rbuckingham** [trufflesuite/ganache#775]
If you manually configure Ganache to listen on a local IP (such as I did on 192.168.1.251) when that IP changes (such as when you go from home to office network) then when it launches it crashes because it automatically tries to listen on the now non-existent IP.

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.1.251:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.1.251","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true,"gasLimit":6721975,"gasPrice":1}
```

**Comment by seesemichaelj** [comment]
For some reason I didn't realize about the whole "laptops move and thus their IP's change" haha. Thank you for reporting this!

We are tracking this issue in #666. We are planning on changing the interface to be a dropdown with the available interfaces rather than a text box. We're also forwarding the user to the config screen rather than the bug screen prompting them to change the host.

You can change the host manually in the `~/Library/Application\ Support/Ganache/Settings` config file to get yourself back up and running.

The fix is scheduled for the next release of Ganache.

Thanks again!
