### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by jasoncodingnow** [trufflesuite/ganache#806]
here is what I tried to do:
launch Ganache;
try deploy my contract;

then Ganache crashed: 

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 0.0.0.0:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"0.0.0.0","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true,"gasLimit":99999999999}
```

**Comment by seesemichaelj** [comment]
The next time ganache crashes, it should have a different error than this. I believe this error is after you clicked "RELAUNCH" from the first crash; there is a known bug which leaves a port open after you click that button and will be fixed in the next release (#665 tracks that).

 You can get your Ganache back up and running by changing the port in the `~/Library/Application\ Support/Ganache/Settings` file.

Thank you so much for reporting; it definitely helps us out! I'm closing this issue as it's more than likely due to #665, but please open up another issue if Ganache crashes again during deployment of your contract; it should be something other than `EADDRINUSE`
