### ISSUE TITLE
Error: sender doesn't have enough funds to send tx

### ISSUE THREAD

**Issue by mallapurbharat** [trufflesuite/ganache#842]
Faced buggy behaviour when sending transaction using Ganache 1.2.0. 
Simplest step to replicate this is to send Ether from one test account (local network) to another. Transaction fails with error "Error: sender doesn't have enough funds to send tx" even though the sender account is having 100 Ether and I'm only sending say 5 Ether.

**_Possibly related to another reported issue #836. Reporting separately since his steps to replicate are different and he faces issue only in particular conditions. My conditions are invariant._**

![send_ether_to_another_account](https://user-images.githubusercontent.com/10878214/42728865-049dad2e-87e3-11e8-9abb-472c32af0df4.png)

![metamask_submit_transaction](https://user-images.githubusercontent.com/10878214/42728864-046dd982-87e3-11e8-9001-b7fcbff8e410.png)

![failed_transaction](https://user-images.githubusercontent.com/10878214/42728863-04440742-87e3-11e8-8f09-15ec0b471184.png)

![error_transaction](https://user-images.githubusercontent.com/10878214/42728862-040fe200-87e3-11e8-9fae-523c47d6dab2.png)

## Expected Behavior
Transaction should go through, as there is ample funds in sender account.
## Current Behavior
Transaction fails with error "Error: sender doesn't have enough funds to send tx" 
## Possible Solution
**Downgrading to Ganache 1.1.0 fixes this issue.**

* Version used: Ganache 1.2.0, Metamask 4.8.0
* Browser: Firefox 61.1.0, Chrome 67.0.3396.99 (64-bit)
* Operating System and version: Ubuntu 16.04 64-bit

**Comment by seesemichaelj** [comment]
Thanks for reporting this! This issue was originally reported under https://github.com/trufflesuite/ganache-core/issues/131 and fixed in https://github.com/trufflesuite/ganache-core/commit/7326b51645be71bd33595b61e8add386ddf0c890

`ganche-cli@6.1.6` and `ganache@1.2.1` fixed this issue!

However, to be thorough, I just now downloaded the `1.2.0` and `1.2.1` AppImage files and ran these on an Ubuntu 16.04 64-bit system. I was able to reproduce the issue in `1.2.0` (following your steps in the picture with different mnemonic/accounts), but was able to successfully send the transaction in `1.2.1`

Please upgrade to 1.2.1; this should fix this issue.

Would love for you to make sure all ganache processes are stopped (rebooting is a for sure way to do it too), and run this minimal set of steps in `1.2.1` and let me know if you are successful or not! Thanks!

**Comment by mallapurbharat** [comment]
Yes, while testing out your suggestions for #841, I also tested out this feature. 

If old ganache processes (1.2.0)  are not running, I find that 1.2.1 works just fine while sending transactions!

Thanks for the quick suggestion!

**Comment by CQBinh** [comment]
Still meet this issue on `ganache v2.0.1` (also `v1.2.1`).
```
Truffle v5.0.15 (core: 5.0.15)
Solidity v0.5.0 (solc-js)
Node v8.12.0
Web3.js v1.0.0-beta.37
```
`pragma solidity 0.4.25;`
