### ISSUE TITLE
System Error when running Ganache 1.2.2 on win32

### ISSUE THREAD

**Issue by aashish-chaubey** [trufflesuite/ganache#934]
PLATFORM: win32
GANACHE VERSION: 1.2.2

EXCEPTION:
```
Error: ENOENT: no such file or directory, open 'C:\Users\AASHIS~1\AppData\Local\Temp\tmp-37628lwxXbSB9ES6F\!trie_db!0xd7a0a17fb510c41ad827b73dd84c684335980049be7a2120d871e8d72dd7e3df'
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.2.2) with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+137ms: Ganache started successfully!
T+137ms: Waiting for requests...
T+18902204ms: eth_sendTransaction
T+18902384ms: eth_unsubscribe
```

**Comment by benjamincburns** [comment]
Hi @aashish-chaubey,

Is this a persistent issue for you, or does it go away the next time you start ganache? Does the directory exist on your machine?

On start ganache creates a temporary directory so that it can store chain data on disk. If this directory is deleted while ganache is running, you'll see this error.

Closing as this is very likely an environment-specific issue. Please comment if the above didn't help you to resolve this!
