### ISSUE TITLE
Ability to delete Workspaces in the Ganache workspace UI

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#957]
Currently a Project can not be deleted from the workspace on the UI.

## Expected Behavior

A user should be able to delete projects they no longer want to see in Ganache

Add the ability to delete projects from the list.

## Current Behavior

Currently the list can become so long that it can take a long amount of time the find the project you wanted to work with. 

## Steps to Reproduce (for bugs)

1. Add a new Truffle Project
2. Try to delete it
3. Currently there is no way to do so on the UI

## Your Environment

* Version used: 2.0.0 Beta
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version: Apache, unsure
* Operating System and version: Mac iOS High Sierra
* Link to your project:

**Comment by seesemichaelj** [comment]
Hey @balexander4 do you mean workspaces (instead of projects; a workspace can have multiple projects) in the below screen?
![image](https://user-images.githubusercontent.com/549323/48225038-aa1e8c00-e369-11e8-9729-17a6b1822386.png)


Projects do currently have a remove button in the settings screen:
![image](https://user-images.githubusercontent.com/549323/48225024-a3901480-e369-11e8-8c8d-b4224176df7b.png)

**Comment by seesemichaelj** [comment]
#996 fixed this
