### ISSUE TITLE
Deploying large contracts fails

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/ganache#981]
When testing with `ganache` we use `allowUnlimitedContractSize` switch to allow contracts bigger than 234576 bytes to be deployed. However an `out of gas` error is thrown even though the contract was created, e.g:

```
Transaction: 0x702c95bfc4324122876c795d6175a62e1a8a75c04d37f3dc30c5a479dda54544
  Contract created: 0xe83ef66e898b65e1e202f3f554897943a0383f29
  Gas usage: 110000000
  Block Number: 430
  Block Time: Tue Apr 28 2020 16:44:45 GMT+0300 (Eastern European Summer Time)
  Runtime Error: out of gas
```

EDIT: The contract that claims to have been created above actually is empty:

```
web3.eth.getCode("0xe83ef66e898b65e1e202f3f554897943a0383f29")
'0x'
```
## Your Environment
* Version used: Ganache CLI v6.9.1 (ganache-core: 2.10.2)
* Version of Truffle/Remix/Other tools used: `etherlime`
* NodeJS Version: 10.12
* Operating System and version (include distro if Linux): OSX
* Link to your project or repro gist: https://github.com/argentlabs/argent-contracts

**Comment by MicaiahReid** [comment]
Hi @elenadimitrova. Apologies for such a late response on this. This doesn't look like it's a bug with ganache, but we definitely could do some better error messaging here. A created address for the contract is computed and the nonce is incremented, but since the sender ran out of gas, no data was actually stored in the contract.

**Comment by its-everdred** [comment]
Sorry for the delay! It does seem like it's worth having a better error message here, but there's some nuance. If you do an `eth_getTransactionReceipt` for this transaction's hash, you'll see that it also includes a `contractAddress` attribute because that address was claimed by the sender and the nonce.  This is expected (albeit strange) behavior that exists in the Ethereum JSON-RPC spec.  

I'm going to close this issue out in favor of a new one that @davidmurdoch will open for the better messaging. Thanks!
